

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


import com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException;
import java.text.DateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Bikash
 */
public class Job_Dept extends javax.swing.JFrame {

    private static final String username = "root";
    private static final String password = "3434!Natun?!%@$#";
    private static final String dataConn = "jdbc:mysql://localhost:3306/ems31?autoReconnect=true&useSSL=false";
   
   Connection sqlConn = null;
   PreparedStatement pst = null;
   ResultSet rs = null;
   int q, i, Job_ID, deleteItem;
   DefaultTableModel d;
   
    public Job_Dept() {
        initComponents();
        upDateDB();
    }
//**************************************FUNCTION START*******************************************************//
      public void upDateDB()
      {
              try
              {
                Class.forName("com.mysql.jdbc.Driver");
                sqlConn = DriverManager.getConnection(dataConn,username,password);        
                pst = sqlConn.prepareStatement("select * from Job_Department");
                
                rs = pst.executeQuery();
                ResultSetMetaData stData = rs.getMetaData();
                
                q = stData.getColumnCount();
                
                DefaultTableModel RecordTable = (DefaultTableModel)txtJob_Depatment_Table.getModel();
                        RecordTable.setRowCount(0);
                        
                        while(rs.next()){
                            Vector columnData = new Vector();
                            
                            for(i = 1;i <= q; i++)
                            {
                                
                                columnData.add(rs.getString("Job_ID"));
                                columnData.add(rs.getString("Dept_Name"));
                                columnData.add(rs.getString("Branch_Name"));
                                columnData.add(rs.getString("Salary_Grade"));
                            }
                            RecordTable.addRow(columnData);
                        }
                    }
                    catch (Exception ex){
                       JOptionPane.showMessageDialog(null, ex);
                    }
              }
    
    
     //**************************************FUNCTION END*******************************************************//

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtJob_ID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtSalaryGrade = new javax.swing.JComboBox<>();
        txtBranch_Name = new javax.swing.JComboBox<>();
        txtDept_Name = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        txtAddNew = new javax.swing.JButton();
        txtUpdateData = new javax.swing.JButton();
        txtPrint = new javax.swing.JButton();
        txtReset = new javax.swing.JButton();
        txtDelete = new javax.swing.JButton();
        txtExit = new javax.swing.JButton();
        txtEmployee = new javax.swing.JButton();
        txtSalary = new javax.swing.JButton();
        txtPayroll = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtJob_Depatment_Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Job_Dept Table");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Job_ID (P.K)");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Dept_Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Branch");

        txtJob_ID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Salary Grade");

        txtSalaryGrade.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSalaryGrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "A", "B", "C", "D" }));

        txtBranch_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtBranch_Name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Dhaka", "Chittagong", "Rajshahi", "Khulna", "Rangpur", "Barisal", "Mymensingh", " " }));

        txtDept_Name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDept_Name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "General Management", "Marketing Department", "Operations Department", "Finance Department", "Sales Department", "Human Resource ", "Purchase Department" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(txtSalaryGrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(txtBranch_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtJob_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtDept_Name, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(278, 278, 278)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtJob_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtDept_Name)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtBranch_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtSalaryGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        jPanel3.setBackground(new java.awt.Color(51, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(95, 158, 160), 4));

        txtAddNew.setBackground(new java.awt.Color(0, 0, 255));
        txtAddNew.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAddNew.setForeground(new java.awt.Color(255, 255, 255));
        txtAddNew.setText("Add New");
        txtAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddNewActionPerformed(evt);
            }
        });

        txtUpdateData.setBackground(new java.awt.Color(0, 0, 255));
        txtUpdateData.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtUpdateData.setForeground(new java.awt.Color(255, 255, 255));
        txtUpdateData.setText("Update Data");
        txtUpdateData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUpdateDataActionPerformed(evt);
            }
        });

        txtPrint.setBackground(new java.awt.Color(0, 0, 255));
        txtPrint.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPrint.setForeground(new java.awt.Color(255, 255, 255));
        txtPrint.setText("Print");
        txtPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrintActionPerformed(evt);
            }
        });

        txtReset.setBackground(new java.awt.Color(0, 0, 255));
        txtReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtReset.setForeground(new java.awt.Color(255, 255, 255));
        txtReset.setText("Reset");
        txtReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResetActionPerformed(evt);
            }
        });

        txtDelete.setBackground(new java.awt.Color(0, 0, 255));
        txtDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtDelete.setForeground(new java.awt.Color(255, 255, 255));
        txtDelete.setText("Delete");
        txtDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeleteActionPerformed(evt);
            }
        });

        txtExit.setBackground(new java.awt.Color(255, 51, 51));
        txtExit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtExit.setForeground(new java.awt.Color(255, 255, 255));
        txtExit.setText("Exit");
        txtExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExitActionPerformed(evt);
            }
        });

        txtEmployee.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEmployee.setText("Employee");
        txtEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeActionPerformed(evt);
            }
        });

        txtSalary.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtSalary.setText("Salay");
        txtSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaryActionPerformed(evt);
            }
        });

        txtPayroll.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPayroll.setText("Payroll");
        txtPayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPayrollActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(txtAddNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUpdateData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtSalary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPayroll, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtReset, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(txtExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUpdateData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPrint, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtReset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPayroll, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Job Department");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(334, 334, 334)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        txtJob_Depatment_Table.setBackground(new java.awt.Color(51, 153, 255));
        txtJob_Depatment_Table.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtJob_Depatment_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Job_ID", "Department Name", "Bramch Name", "Salary Grade"
            }
        ));
        txtJob_Depatment_Table.setRowHeight(25);
        txtJob_Depatment_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtJob_Depatment_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txtJob_Depatment_Table);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1350, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeActionPerformed
        // TODO add your handling code here:
        Employee d = new Employee();
        this.setVisible(false);
        d.setVisible(true);
    }//GEN-LAST:event_txtEmployeeActionPerformed

    private void txtSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaryActionPerformed
        // TODO add your handling code here:
        Salary d = new Salary();
        this.setVisible(false);
        d.setVisible(true);
    }//GEN-LAST:event_txtSalaryActionPerformed

    private void txtPayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPayrollActionPerformed
        // TODO add your handling code here:
        Payroll d = new Payroll();
        this.setVisible(false);
        d.setVisible(true);
    }//GEN-LAST:event_txtPayrollActionPerformed
 private JFrame frame;
    private void txtExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExitActionPerformed
        // TODO add your handling code here:
                  frame = new JFrame("Exit");
     if(JOptionPane.showConfirmDialog(frame, "confirm if you want to exit","Employee Management System",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION)
     {
         //System.exit(0);
         Admin_Login L = new Admin_Login();  
        this.setVisible(false);
        L.setVisible(true);
     } 
    }//GEN-LAST:event_txtExitActionPerformed

    private void txtAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddNewActionPerformed
        // TODO add your handling code here:
           if (txtJob_ID.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Job ID is empty");
            return;
        }
        if (txtDept_Name.getSelectedItem().toString().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Department Name is empty");
            return;
        }
        if (txtBranch_Name.getSelectedItem().toString().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Branch Name is empty");
            return;
        }
          if (txtSalaryGrade.getSelectedItem().toString().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Salary Group is empty");
            return;
        }
         
        try
              {
                Class.forName("com.mysql.jdbc.Driver");
                sqlConn = DriverManager.getConnection(dataConn,username,password);        
                pst = sqlConn.prepareStatement("insert into Job_Department(Job_ID,Dept_Name,Branch_Name," + "Salary_Grade)value(?,?,?,?)");
                
                pst.setString(1, txtJob_ID.getText());
                pst.setString(2, txtDept_Name.getSelectedItem().toString());
                pst.setString(3, txtBranch_Name.getSelectedItem().toString());
                pst.setString(4, txtSalaryGrade.getSelectedItem().toString());
                
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record Added");
                upDateDB();
                
              }
        catch(ClassNotFoundException ex){
        java.util.logging.Logger.getLogger(Job_Dept.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
                
        } 
//        catch (MySQLIntegrityConstraintViolationException ex) {
//            // show duplicate jobid insert error dialog
//            JOptionPane.showMessageDialog(this, "This Emp_ID Already Registered", "Emp_ID ERROR", JOptionPane.ERROR_MESSAGE);
//        }
        catch(SQLException ex){
           java.util.logging.Logger.getLogger(Job_Dept.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_txtAddNewActionPerformed

    private void txtUpdateDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUpdateDataActionPerformed
        // TODO add your handling code here:
        DefaultTableModel RecordTable = (DefaultTableModel)txtJob_Depatment_Table.getModel();
        int SelectedRows = txtJob_Depatment_Table.getSelectedRow();
        try
              {
                Job_ID = Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());  
                Class.forName("com.mysql.jdbc.Driver");
                sqlConn = DriverManager.getConnection(dataConn,username,password);        
                pst = sqlConn.prepareStatement("update Job_Department set Dept_name=?,Branch_Name=?,"
                        + "Salary_Grade=? where Job_ID =?");
                
                pst.setString(1, txtDept_Name.getSelectedItem().toString());
                pst.setString(2, txtBranch_Name.getSelectedItem().toString());
                pst.setString(3, txtSalaryGrade.getSelectedItem().toString());
                pst.setString(4, String.valueOf(Job_ID));
                
                
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Record updated");
                upDateDB();
                
              }
        catch(ClassNotFoundException ex){
        java.util.logging.Logger.getLogger(Job_Dept.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
                
        } catch(SQLException ex){
           java.util.logging.Logger.getLogger(Job_Dept.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_txtUpdateDataActionPerformed

    private void txtPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrintActionPerformed
        // TODO add your handling code here:
            MessageFormat header = new MessageFormat("Job Department");
        MessageFormat footer = new MessageFormat("Page [0, number, integer]");
        
        try
        {
            txtJob_Depatment_Table.print(JTable.PrintMode.FIT_WIDTH,header, footer);
        }
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("No Printer found", e.getMessage());
        }
    }//GEN-LAST:event_txtPrintActionPerformed

    private void txtResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResetActionPerformed
        // TODO add your handling code here:
        txtJob_ID.setText("");
        txtDept_Name.setSelectedIndex(-1);
        txtBranch_Name.setSelectedIndex(-1);
       txtSalaryGrade.setSelectedIndex(-1);
    }//GEN-LAST:event_txtResetActionPerformed

    private void txtDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeleteActionPerformed
        // TODO add your handling code here:
          DefaultTableModel RecordTable = (DefaultTableModel)txtJob_Depatment_Table.getModel();
         int SelectedRows = txtJob_Depatment_Table.getSelectedRow();
         
         try
         {
             Job_ID = Integer.parseInt(RecordTable.getValueAt(SelectedRows, 0).toString());
             
             deleteItem = JOptionPane.showConfirmDialog(null," Confirm if you want to delete item","Warning",JOptionPane.YES_NO_OPTION);
             if(deleteItem == JOptionPane.YES_NO_OPTION)
             {
                 Class.forName("com.mysql.jdbc.Driver");
                sqlConn = DriverManager.getConnection(dataConn,username,password); 
                pst = sqlConn.prepareStatement("delete from Job_Department where Job_ID =?");
                
                pst.setInt(1, Job_ID);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this, "Recorded delete");
                upDateDB();
                
                        txtDept_Name.getSelectedItem().toString();
                        txtBranch_Name.getSelectedItem().toString();
                        txtSalaryGrade.getSelectedItem().toString();
             }
         }
         
        catch(ClassNotFoundException ex){
        java.util.logging.Logger.getLogger(Job_Dept.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
                
        } 
         catch (MySQLIntegrityConstraintViolationException ex) {
            // show duplicate jobid insert error dialog
            JOptionPane.showMessageDialog(this, "Salary & Payroll References Job ID ", "References Job ID", JOptionPane.ERROR_MESSAGE);
        }
         catch(SQLException ex){
            System.err.println(ex);
        }
    }//GEN-LAST:event_txtDeleteActionPerformed

    private void txtJob_Depatment_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJob_Depatment_TableMouseClicked
        // TODO add your handling code here:
         DefaultTableModel RecordTable = (DefaultTableModel)txtJob_Depatment_Table.getModel();
        int SelectedRows = txtJob_Depatment_Table.getSelectedRow();

        d = (DefaultTableModel)txtJob_Depatment_Table.getModel();
        int selectIndex = txtJob_Depatment_Table.getSelectedRow();

        txtDept_Name.setSelectedItem(d.getValueAt(selectIndex, 1).toString());
        txtBranch_Name.setSelectedItem(d.getValueAt(selectIndex, 2).toString());
        txtSalaryGrade.setSelectedItem(d.getValueAt(selectIndex, 3).toString());
    }//GEN-LAST:event_txtJob_Depatment_TableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Job_Dept().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton txtAddNew;
    private javax.swing.JComboBox<String> txtBranch_Name;
    private javax.swing.JButton txtDelete;
    private javax.swing.JComboBox<String> txtDept_Name;
    private javax.swing.JButton txtEmployee;
    private javax.swing.JButton txtExit;
    private javax.swing.JTable txtJob_Depatment_Table;
    private javax.swing.JTextField txtJob_ID;
    private javax.swing.JButton txtPayroll;
    private javax.swing.JButton txtPrint;
    private javax.swing.JButton txtReset;
    private javax.swing.JButton txtSalary;
    private javax.swing.JComboBox<String> txtSalaryGrade;
    private javax.swing.JButton txtUpdateData;
    // End of variables declaration//GEN-END:variables
}
